/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package xbank;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author nikunj
 */

public class CardReq extends javax.swing.JFrame {
    
    Database db;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CardReq.class.getName());

    /**
     * Creates new form ATMReq
     */
    public CardReq() {
        initComponents();
        db = new Database();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ATM Card Req");

        jLabel2.setText("Enter Account Number");

        jButton1.setText("Assign ATM Card");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debit", "Credit" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(145, 145, 145)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(132, 132, 132)
                            .addComponent(jButton1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        String accountNo = jTextField1.getText().trim();
        String cardType = (String) jComboBox1.getSelectedItem();

        if (accountNo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an account number.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (db == null || db.con == null) {
             JOptionPane.showMessageDialog(this, "Database connection is not available.", "Error", JOptionPane.ERROR_MESSAGE);
             return;
        }

        try {
            // Step 1: Check if account number exists in the customer table
            String checkSql = "SELECT COUNT(*) FROM customer WHERE account_no = ?";
            PreparedStatement checkStmt = db.con.prepareStatement(checkSql);
            checkStmt.setString(1, accountNo);
            
            ResultSet rs = checkStmt.executeQuery();
            
            if (rs.next() && rs.getInt(1) > 0) {
                // Account exists, proceed to create card
                
                // Step 2: Generate random card details
                Random rand = new Random();
                
                // Generate 16-digit card number (to match your DB constraint '^[0-9]{16}$')
                String cardNoStr = "" + (1000 + rand.nextInt(9000)) 
                                    + (1000 + rand.nextInt(9000)) 
                                    + (1000 + rand.nextInt(9000)) 
                                    + (1000 + rand.nextInt(9000));
                
                // Generate 3-digit CVV (to match your DB constraint '^[0-9]{3}$')
                String cvvStr = String.format("%03d", rand.nextInt(1000));
                
                // Generate 4-digit PIN (as requested, fits in VARCHAR2(6))
                String pinStr = String.format("%04d", rand.nextInt(10000));

                
                // Step 3: Insert new card details into the 'cards' table
                String insertSql = "INSERT INTO cards (card_no, account_no, cvv, atm_pin, card_type) VALUES (?, ?, ?, ?, ?)";
                PreparedStatement insertStmt = db.con.prepareStatement(insertSql);
                
                insertStmt.setString(1, cardNoStr);
                insertStmt.setString(2, accountNo);
                insertStmt.setString(3, cvvStr);
                insertStmt.setString(4, pinStr);
                insertStmt.setString(5, cardType);
                
                int rowsAffected = insertStmt.executeUpdate();
                
                if (rowsAffected > 0) {
                    // Step 4: Get the generated dates from the DB to show the user
                    String selectSql = "SELECT issue_date, expiry_date FROM cards WHERE card_no = ?";
                    PreparedStatement selectStmt = db.con.prepareStatement(selectSql);
                    selectStmt.setString(1, cardNoStr);
                    ResultSet rsCard = selectStmt.executeQuery();
                    
                    String issueDate = "N/A";
                    String expiryDate = "N/A";
                            
                    if (rsCard.next()) {
                        issueDate = rsCard.getDate("issue_date").toString();
                        expiryDate = rsCard.getDate("expiry_date").toString();
                    }
                    
                    // Step 5: Show success message with all details
                    String message = "Card Assigned Successfully!\n\n"
                            + "Account Number: " + accountNo + "\n"
                            + "Card Number: " + cardNoStr + "\n"
                            + "CVV: " + cvvStr + "\n"
                            + "ATM PIN: " + pinStr + "\n"
                            + "Card Type: " + cardType + "\n"
                            + "Issue Date: " + issueDate + "\n"
                            + "Expiry Date: " + expiryDate;
                    
                    JOptionPane.showMessageDialog(this, message, "Success", JOptionPane.INFORMATION_MESSAGE);
                    
                    // Close this window (this was in your original code)
                    this.dispose(); 
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to create card.", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                // Account does not exist
                JOptionPane.showMessageDialog(this, "Account number " + accountNo + " does not exist.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CardReq().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}



// /*
//  * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
//  * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
//  */
// package xbank;

// // --- IMPORTS ADDED ---
// import java.sql.PreparedStatement;
// import java.sql.ResultSet;
// import java.sql.SQLException;
// import java.util.Random;
// import javax.swing.JOptionPane;
// // ---------------------

// /**
//  *
//  * @author harsh
//  */
// public class CardReq extends javax.swing.JFrame {
    
//     // --- VARIABLE ADDED ---
//     Database db;
//     // ----------------------
    
//     private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CardReq.class.getName());

//     /**
//      * Creates new form ATMReq
//      */
//     public CardReq() {
//         initComponents();
//         // --- LOGIC ADDED ---
//         db = new Database(); // Initialize the database connection
//         // -------------------
//     }

//     /**
//      * This method is called from within the constructor to initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is always
//      * regenerated by the Form Editor.
//      */
//     @SuppressWarnings("unchecked")
//     // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//     private void initComponents() {

//         jLabel1 = new javax.swing.JLabel();
//         jLabel2 = new javax.swing.JLabel();
//         jTextField1 = new javax.swing.JTextField();
//         jButton1 = new javax.swing.JButton();
//         jComboBox1 = new javax.swing.JComboBox<>();

//         setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

//         jLabel1.setText("ATM Card Req");

//         jLabel2.setText("Enter Account Number");

//         jButton1.setText("Assign ATM Card");
//         jButton1.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jButton1ActionPerformed(evt);
//             }
//         });

//         jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debit", "Credit" }));
//         jComboBox1.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jComboBox1ActionPerformed(evt);
//             }
//         });

//         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//         getContentPane().setLayout(layout);
//         layout.setHorizontalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                 .addContainerGap(62, Short.MAX_VALUE)
//                 .addComponent(jLabel2)
//                 .addGap(18, 18, 18)
//                 .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(46, 46, 46))
//             .addGroup(layout.createSequentialGroup()
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                     .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                         .addGroup(layout.createSequentialGroup()
//                             .addGap(145, 145, 145)
//                             .addComponent(jLabel1))
//                         .addGroup(layout.createSequentialGroup()
//                             .addGap(132, 132, 132)
//                             .addComponent(jButton1))))
//                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//         );
//         layout.setVerticalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addGap(23, 23, 23)
//                 .addComponent(jLabel1)
//                 .addGap(27, 27, 27)
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel2)
//                     .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(18, 18, 18)
//                 .addComponent(jButton1)
//                 .addContainerGap(25, Short.MAX_VALUE))
//         );

//         pack();
//     }// </editor-fold>                        

//     // --- ENTIRE BUTTON LOGIC REPLACED ---
//     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
//         String accountNo = jTextField1.getText().trim();
//         String cardType = (String) jComboBox1.getSelectedItem();

//         if (accountNo.isEmpty()) {
//             JOptionPane.showMessageDialog(this, "Please enter an account number.", "Error", JOptionPane.ERROR_MESSAGE);
//             return;
//         }
        
//         if (db == null || db.con == null) {
//              JOptionPane.showMessageDialog(this, "Database connection is not available.", "Error", JOptionPane.ERROR_MESSAGE);
//              return;
//         }

//         try {
//             // Step 1: Check if account number exists in the customer table
//             String checkSql = "SELECT COUNT(*) FROM customer WHERE account_no = ?";
//             PreparedStatement checkStmt = db.con.prepareStatement(checkSql);
//             checkStmt.setString(1, accountNo);
            
//             ResultSet rs = checkStmt.executeQuery();
            
//             if (rs.next() && rs.getInt(1) > 0) {
//                 // Account exists, proceed to create card
                
//                 // Step 2: Generate random card details
//                 Random rand = new Random();
                
//                 // Generate 16-digit card number (to match your DB constraint '^[0-9]{16}$')
//                 String cardNoStr = "" + (1000 + rand.nextInt(9000)) 
//                                     + (1000 + rand.nextInt(9000)) 
//                                     + (1000 + rand.nextInt(9000)) 
//                                     + (1000 + rand.nextInt(9000));
                
//                 // Generate 3-digit CVV (to match your DB constraint '^[0-9]{3}$')
//                 String cvvStr = String.format("%03d", rand.nextInt(1000));
                
//                 // Generate 4-digit PIN (as requested, fits in VARCHAR2(6))
//                 String pinStr = String.format("%04d", rand.nextInt(10000));

                
//                 // Step 3: Insert new card details into the 'cards' table
//                 String insertSql = "INSERT INTO cards (card_no, account_no, cvv, atm_pin, card_type) VALUES (?, ?, ?, ?, ?)";
//                 PreparedStatement insertStmt = db.con.prepareStatement(insertSql);
                
//                 insertStmt.setString(1, cardNoStr);
//                 insertStmt.setString(2, accountNo);
//                 insertStmt.setString(3, cvvStr);
//                 insertStmt.setString(4, pinStr);
//                 insertStmt.setString(5, cardType);
                
//                 int rowsAffected = insertStmt.executeUpdate();
                
//                 if (rowsAffected > 0) {
//                     // Step 4: Get the generated dates from the DB to show the user
//                     String selectSql = "SELECT issue_date, expiry_date FROM cards WHERE card_no = ?";
//                     PreparedStatement selectStmt = db.con.prepareStatement(selectSql);
//                     selectStmt.setString(1, cardNoStr);
//                     ResultSet rsCard = selectStmt.executeQuery();
                    
//                     String issueDate = "N/A";
//                     String expiryDate = "N/A";
                            
//                     if (rsCard.next()) {
//                         issueDate = rsCard.getDate("issue_date").toString();
//                         expiryDate = rsCard.getDate("expiry_date").toString();
//                     }
                    
//                     // Step 5: Show success message with all details
//                     String message = "Card Assigned Successfully!\n\n"
//                             + "Account Number: " + accountNo + "\n"
//                             + "Card Number: " + cardNoStr + "\n"
//                             + "CVV: " + cvvStr + "\n"
//                             + "ATM PIN: " + pinStr + "\n"
//                             + "Card Type: " + cardType + "\n"
//                             + "Issue Date: " + issueDate + "\n"
//                             + "Expiry Date: " + expiryDate;
                    
//                     JOptionPane.showMessageDialog(this, message, "Success", JOptionPane.INFORMATION_MESSAGE);
                    
//                     // Close this window (this was in your original code)
//                     this.dispose(); 
                    
//                 } else {
//                     JOptionPane.showMessageDialog(this, "Failed to create card.", "Error", JOptionPane.ERROR_MESSAGE);
//                 }

//             } else {
//                 // Account does not exist
//                 JOptionPane.showMessageDialog(this, "Account number " + accountNo + " does not exist.", "Error", JOptionPane.ERROR_MESSAGE);
//             }

//         } catch (SQLException e) {
//             e.printStackTrace();
//             JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//         }
//     }                                        
//     // ------------------------------------

//     private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
//         // TODO add your handling code here:
//     }                                          

//     /**
//      * @param args the command line arguments
//      */
//     public static void main(String args[]) {
//         /* Set the Nimbus look and feel */
//         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//         /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//          * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//          */
//         try {
//             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                 if ("Nimbus".equals(info.getName())) {
//                     javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                     break;
//                 }
//             }
//         } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//             logger.log(java.util.logging.Level.SEVERE, null, ex);
//         }
//         //</editor-fold>

//         /* Create and display the form */
//         java.awt.EventQueue.invokeLater(() -> new CardReq().setVisible(true));
//     }

//     // Variables declaration - do not modify                     
//     private javax.swing.JButton jButton1;
//     private javax.swing.JComboBox<String> jComboBox1;
//     private javax.swing.JLabel jLabel1;
//     private javax.swing.JLabel jLabel2;
//     private javax.swing.JTextField jTextField1;
//     // End of variables declaration                   
// }