/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package xbank;
import javax.swing.JOptionPane;
/**
 *
 * @author harsh
 */
public class LoginPage extends javax.swing.JFrame {
    Database db;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginPage.class.getName());

    /**
     * Creates new form HomePage
     */
    public LoginPage() {
        initComponents();
        jButton2.setVisible(false);
        db = new Database();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to XBank");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Employee", "Manager" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Select your role");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("ID No.");

        jLabel4.setText("Password");

        jLabel5.setText("Dont have account yet , Register now");

        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jButton2)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String selectedRole = (String) jComboBox1.getSelectedItem();
        if ("Customer".equals(selectedRole)) {
            jButton2.setVisible(true);
        } else {
            jButton2.setVisible(false);
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String selectedOption = (String) jComboBox1.getSelectedItem();
        String id = jTextField1.getText().trim();
        char[] passwordChars = jPasswordField1.getPassword();
        String password = new String(passwordChars);
        System.out.println("ID: " + id);
        System.out.println("Password: " + password);
   
        if (selectedOption.equals("Customer")) {
            try
            {
                String sql = "SELECT account_no, password FROM netbanking WHERE account_no = '" 
                    + id + "'";
                System.out.println(sql);
                db.rs = db.stmt.executeQuery(sql);
                if(db.rs.next())
                { 
                    String accNo = db.rs.getString("ACCOUNT_NO");
                    String dbPassword = db.rs.getString("PASSWORD");
                    System.out.println("Account No: " + accNo);
                    System.out.println("database password: " + dbPassword);
                    if (password.equals(dbPassword)) {
                        
                        JOptionPane.showMessageDialog(this, "Login successful!");
                        new CustomerDashboard(accNo).setVisible(true);
                        this.dispose();
                    }
                    else {
                        
                        JOptionPane.showMessageDialog(this, "Password mismatch!", "Error", JOptionPane.ERROR_MESSAGE);
                        new xbank.LoginPage().setVisible(true);
                        this.dispose();
                    }
                } 
                else {
                   
                   JOptionPane.showMessageDialog(this, "ID not present!", "Error", JOptionPane.ERROR_MESSAGE);
                   new xbank.LoginPage().setVisible(true);
                   this.dispose();
                }
                
            }
            catch (Exception e) {
                e.printStackTrace();
        
            }
            
        } 
        else if (selectedOption.equals("Employee")) {
            try
            {
                String sql = "SELECT E_Name,PIN FROM EMPLOYEE WHERE E_ID = '"
                        +id+"' AND POST = '"+selectedOption.toLowerCase()+"'";
                System.out.println(sql);
                db.rs = db.stmt.executeQuery(sql);
                
                if(db.rs.next())
                { 
                    String name = db.rs.getString("E_Name");
                    String dbPassword = db.rs.getString("PIN");
                    System.out.println("Employee Name: " + name);
                    System.out.println("database password: " + dbPassword);
                    if (password.equals(dbPassword)) {
                        
                        JOptionPane.showMessageDialog(this, "Login successful!");
                        new EmployeeDashboard(id).setVisible(true);
                        this.dispose();
                    } 
                    else {
                        
                        JOptionPane.showMessageDialog(this, "Password mismatch!", "Error", JOptionPane.ERROR_MESSAGE);
                        new LoginPage().setVisible(true);
                        this.dispose();
                    }
                } 
                else {
                   
                   JOptionPane.showMessageDialog(this, "Employee ID not present!", "Error", JOptionPane.ERROR_MESSAGE);
                   new LoginPage().setVisible(true);
                   this.dispose();
                }

            }
            catch (Exception e) {
                e.printStackTrace();
        
            }
           
        } 
        else if (selectedOption.equals("Manager")) {
            try
            {
                String sql = "SELECT E_Name,PIN FROM EMPLOYEE WHERE E_ID = '"
                        +id+"' AND POST = '"+selectedOption.toLowerCase()+"'";
                System.out.println(sql);
                db.rs = db.stmt.executeQuery(sql);
                
                if(db.rs.next())
                { 
                    String name = db.rs.getString("E_Name");
                    String dbPassword = db.rs.getString("PIN");
                    System.out.println("Employee Name: " + name);
                    System.out.println("database password: " + dbPassword);
                    if (password.equals(dbPassword)) {
                        
                        JOptionPane.showMessageDialog(this, "Login successful!");
                        new ManagerDashboard(id).setVisible(true);
                        this.dispose(); // close login page
                    } 
                    else {
                        
                        JOptionPane.showMessageDialog(this, "Password mismatch!", "Error", JOptionPane.ERROR_MESSAGE);
                        new LoginPage().setVisible(true);
                        this.dispose();
                    }
                } 
                else {
                   
                   JOptionPane.showMessageDialog(this, "Employee ID not present!", "Error", JOptionPane.ERROR_MESSAGE);
                   new LoginPage().setVisible(true);
                   this.dispose();
                }

            }
            catch (Exception e) {
                e.printStackTrace();
        
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new NetBankingRegister().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
